---
- hosts: all
  vars:
    ansible_ssh_private_key_file: "~/.ssh/minnacraft.pem"
    ansible_user: ubuntu

    minecraft_max_memory: 6144 # 6GB
    minecraft_whitelist: []
    minecraft_ops: []
    minecraft_server_properties: {} # server-port: 25565

  gather_facts: yes

  pre_tasks:
    - name: 'install python2'
      # ansible needs python 2, newer systems tend to ship
      # with python 3
      raw: apt-get update && sudo apt-get -y install python-simplejson python-dev python-pip
      become: true # become_user defaults to root
      become_user: root
    - name: 'Ensure GMT'
      timezone:
        name: Europe/London
      become: true
    - name: 'Use ntp'
      apt:
        name: ntp
        state: present
      become: true
  tasks:
    - name: update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600
      become: true
    - name: Ensure automated security updates
      apt:
        name: unattended-upgrades
        state: present
      become: true

    - name: install java, because the galaxy doesn't sudo it for some reason
      apt:
        name: default-jdk
        state: present
      become: true

  roles:
    - devops-coop.minecraft
